# Generated by Django 4.2.3 on 2023-07-15 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraperapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisite',
            name='subject_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='scraperapp.subject'),
        ),
    ]
